site_name: MEGR 2157 – Design Portfolio
site_description: Design portfolio documentation, built with the Analyze / Decide / Communicate framework

theme:
  name: material
  palette:
    primary: pink
  features:
    - navigation.instant
    - navigation.tracking

nav:
  - Home: index.md
  - About Me: aboutme/index.md
  - Portfolio Overview: portfolio-overview.md
  - Assignments:
      - A1: assignments/A01-Create Portfolio/index.md
      - A2: assignments/A02-Design with Basic Stress/index.md
      - A3: assignments/A03-Parametric and FEA/index.md
      - A4: assignments/A04-Moror Mount/index.md
      - A5: assignments/A05-Bracket Design/index.md
      - A6: assignments/A06-Bracket Drawing/index.md
      - A7: assignments/A07-FEA on Bracket/index.md
      - A8: assignments/A08-Gear Box Design/index.md
      - A9: assignments/A09-PPulley System Design/index.md
      - A10: assignments/A10-Lead Screw Design/index.md
      - A11: assignments/A11-Motor Selection Design/index.md
